"""
    Secret Server Rest API

    REST API documentation for Secret Server. This document describes how to use the REST API. All requests require an authentication token; please see the <a href=\"../OAuth/\">authentication document</a> for more information. The <a href=\"swagger.json\">Swagger specification</a> for this API is also available.  # Authentication  <!-- ReDoc-Inject: <security-definitions> -->  # noqa: E501

    The version of the OpenAPI document: 11.2.2
    Contact: info@authomize.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import secret_server_openapiclient
from secret_server_openapiclient.model.secret_detail_launcher import SecretDetailLauncher
from secret_server_openapiclient.model.view_field_value_of_boolean import ViewFieldValueOfBoolean
from secret_server_openapiclient.model.view_field_value_of_optional_date_time import ViewFieldValueOfOptionalDateTime
from secret_server_openapiclient.model.view_field_value_of_optional_int32 import ViewFieldValueOfOptionalInt32
from secret_server_openapiclient.model.view_field_value_of_secret_detail_heartbeat_status import ViewFieldValueOfSecretDetailHeartbeatStatus
from secret_server_openapiclient.model.view_field_value_of_string import ViewFieldValueOfString
from secret_server_openapiclient.model.view_template_field_of_string import ViewTemplateFieldOfString
globals()['SecretDetailLauncher'] = SecretDetailLauncher
globals()['ViewFieldValueOfBoolean'] = ViewFieldValueOfBoolean
globals()['ViewFieldValueOfOptionalDateTime'] = ViewFieldValueOfOptionalDateTime
globals()['ViewFieldValueOfOptionalInt32'] = ViewFieldValueOfOptionalInt32
globals()['ViewFieldValueOfSecretDetailHeartbeatStatus'] = ViewFieldValueOfSecretDetailHeartbeatStatus
globals()['ViewFieldValueOfString'] = ViewFieldValueOfString
globals()['ViewTemplateFieldOfString'] = ViewTemplateFieldOfString
from secret_server_openapiclient.model.secret_detail_general_view_model import SecretDetailGeneralViewModel


class TestSecretDetailGeneralViewModel(unittest.TestCase):
    """SecretDetailGeneralViewModel unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testSecretDetailGeneralViewModel(self):
        """Test SecretDetailGeneralViewModel"""
        # FIXME: construct object with mandatory attributes with example values
        # model = SecretDetailGeneralViewModel()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
