"""
    Secret Server Rest API

    REST API documentation for Secret Server. This document describes how to use the REST API. All requests require an authentication token; please see the <a href=\"../OAuth/\">authentication document</a> for more information. The <a href=\"swagger.json\">Swagger specification</a> for this API is also available.  # Authentication  <!-- ReDoc-Inject: <security-definitions> -->  # noqa: E501

    The version of the OpenAPI document: 11.2.2
    Contact: info@authomize.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import secret_server_openapiclient
from secret_server_openapiclient.model.view_field_value_of_boolean import ViewFieldValueOfBoolean
from secret_server_openapiclient.model.view_field_value_of_date_time import ViewFieldValueOfDateTime
from secret_server_openapiclient.model.view_field_value_of_optional_boolean import ViewFieldValueOfOptionalBoolean
from secret_server_openapiclient.model.view_field_value_of_optional_int32 import ViewFieldValueOfOptionalInt32
from secret_server_openapiclient.model.view_field_value_of_optional_schedule_monthly_day_order_type import ViewFieldValueOfOptionalScheduleMonthlyDayOrderType
from secret_server_openapiclient.model.view_field_value_of_optional_schedule_monthly_day_type import ViewFieldValueOfOptionalScheduleMonthlyDayType
from secret_server_openapiclient.model.view_field_value_of_optional_schedule_monthly_type import ViewFieldValueOfOptionalScheduleMonthlyType
from secret_server_openapiclient.model.view_field_value_of_report_subscriber_array import ViewFieldValueOfReportSubscriberArray
from secret_server_openapiclient.model.view_field_value_of_schedule_change_type import ViewFieldValueOfScheduleChangeType
from secret_server_openapiclient.model.view_field_value_of_string import ViewFieldValueOfString
globals()['ViewFieldValueOfBoolean'] = ViewFieldValueOfBoolean
globals()['ViewFieldValueOfDateTime'] = ViewFieldValueOfDateTime
globals()['ViewFieldValueOfOptionalBoolean'] = ViewFieldValueOfOptionalBoolean
globals()['ViewFieldValueOfOptionalInt32'] = ViewFieldValueOfOptionalInt32
globals()['ViewFieldValueOfOptionalScheduleMonthlyDayOrderType'] = ViewFieldValueOfOptionalScheduleMonthlyDayOrderType
globals()['ViewFieldValueOfOptionalScheduleMonthlyDayType'] = ViewFieldValueOfOptionalScheduleMonthlyDayType
globals()['ViewFieldValueOfOptionalScheduleMonthlyType'] = ViewFieldValueOfOptionalScheduleMonthlyType
globals()['ViewFieldValueOfReportSubscriberArray'] = ViewFieldValueOfReportSubscriberArray
globals()['ViewFieldValueOfScheduleChangeType'] = ViewFieldValueOfScheduleChangeType
globals()['ViewFieldValueOfString'] = ViewFieldValueOfString
from secret_server_openapiclient.model.schedule_view_model import ScheduleViewModel


class TestScheduleViewModel(unittest.TestCase):
    """ScheduleViewModel unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testScheduleViewModel(self):
        """Test ScheduleViewModel"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ScheduleViewModel()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
