"""
    Secret Server Rest API

    REST API documentation for Secret Server. This document describes how to use the REST API. All requests require an authentication token; please see the <a href=\"../OAuth/\">authentication document</a> for more information. The <a href=\"swagger.json\">Swagger specification</a> for this API is also available.  # Authentication  <!-- ReDoc-Inject: <security-definitions> -->  # noqa: E501

    The version of the OpenAPI document: 11.2.2
    Contact: info@authomize.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import secret_server_openapiclient
from secret_server_openapiclient.model.character_set_summary import CharacterSetSummary
from secret_server_openapiclient.model.password_dictionary_summary import PasswordDictionarySummary
from secret_server_openapiclient.model.password_requirement_rule_summary import PasswordRequirementRuleSummary
globals()['CharacterSetSummary'] = CharacterSetSummary
globals()['PasswordDictionarySummary'] = PasswordDictionarySummary
globals()['PasswordRequirementRuleSummary'] = PasswordRequirementRuleSummary
from secret_server_openapiclient.model.password_requirement_model import PasswordRequirementModel


class TestPasswordRequirementModel(unittest.TestCase):
    """PasswordRequirementModel unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPasswordRequirementModel(self):
        """Test PasswordRequirementModel"""
        # FIXME: construct object with mandatory attributes with example values
        # model = PasswordRequirementModel()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
