"""
    Secret Server Rest API

    REST API documentation for Secret Server. This document describes how to use the REST API. All requests require an authentication token; please see the <a href=\"../OAuth/\">authentication document</a> for more information. The <a href=\"swagger.json\">Swagger specification</a> for this API is also available.  # Authentication  <!-- ReDoc-Inject: <security-definitions> -->  # noqa: E501

    The version of the OpenAPI document: 11.2.2
    Contact: info@authomize.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import secret_server_openapiclient
from secret_server_openapiclient.model.secret_policy_general_items_update_model import SecretPolicyGeneralItemsUpdateModel
from secret_server_openapiclient.model.secret_policy_launcher_items_update_model import SecretPolicyLauncherItemsUpdateModel
from secret_server_openapiclient.model.secret_policy_rpc_items_update_model import SecretPolicyRpcItemsUpdateModel
from secret_server_openapiclient.model.secret_policy_security_items_update_model import SecretPolicySecurityItemsUpdateModel
from secret_server_openapiclient.model.update_field_value_of_boolean import UpdateFieldValueOfBoolean
from secret_server_openapiclient.model.update_field_value_of_string import UpdateFieldValueOfString
globals()['SecretPolicyGeneralItemsUpdateModel'] = SecretPolicyGeneralItemsUpdateModel
globals()['SecretPolicyLauncherItemsUpdateModel'] = SecretPolicyLauncherItemsUpdateModel
globals()['SecretPolicyRpcItemsUpdateModel'] = SecretPolicyRpcItemsUpdateModel
globals()['SecretPolicySecurityItemsUpdateModel'] = SecretPolicySecurityItemsUpdateModel
globals()['UpdateFieldValueOfBoolean'] = UpdateFieldValueOfBoolean
globals()['UpdateFieldValueOfString'] = UpdateFieldValueOfString
from secret_server_openapiclient.model.secret_policy_update_model_v2 import SecretPolicyUpdateModelV2


class TestSecretPolicyUpdateModelV2(unittest.TestCase):
    """SecretPolicyUpdateModelV2 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testSecretPolicyUpdateModelV2(self):
        """Test SecretPolicyUpdateModelV2"""
        # FIXME: construct object with mandatory attributes with example values
        # model = SecretPolicyUpdateModelV2()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
